import 'dart:math';

import 'package:flutter/material.dart';

void main(){
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  List<String> _frases = null;
  int _numeroDaSorte = 0;
  bool primeiraFrase = true;

  void _incrementCounter() {
    _frases = primeiraFrase ? _frases = getFrases() : primeiraFrase = false;
    setState(() {
      _numeroDaSorte = new Random().nextInt(_frases?.length);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Frases do Dia"
        ),
        backgroundColor: Colors.green,
      ),
      body: Container(
        padding: EdgeInsets.all(15),
        width: double.infinity,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Image.asset("images/logo.png"),
            Text(
                _frases != null ? _frases[_numeroDaSorte] : "Clique no botão para gerar uma frase",
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
            ),
            RaisedButton(
                onPressed: _incrementCounter,
                color: Colors.green,
                child: Text(
                  "Nova Frase",
                  style: TextStyle(color: Colors.white),
                ),
            )
          ],
        ),
      ),
    );
  }

  List<String> getFrases(){
    return [
    'Os problemas são oportunidades para se mostrar o que sabe.  (Duke Ellington)',
    'Nossos fracassos, às vezes, são mais frutíferos do que os êxitos. (Henry Ford)',
    'Tente de novo. Fracasse de novo. Mas fracasse melhor. (Samuel Beckett)',
    'É costume de um tolo, quando erra, queixar-se dos outros. É costume de um sábio queixar-se de si mesmo. (Sócrates)',
    'O verdadeiro heroísmo consiste em persistir por mais um momento, quando tudo parece perdido. (W. F. Grenfel)',
    'Cada cliente é como se fosse primeiro e único. (Norman Bawes)',
    'Mesmo que já tenhas feito uma longa caminhada, há sempre um novo caminho a fazer. (Santo Agostinho)',
    'Vender é construir uma ponte entre você e seu cliente e fazê-lo atravessar para o seu lado. (Ciclo dos Profissionais de Venda)',
    'Na prosperidade, nossos amigos nos conhecem; na adversidade, nós é que conhecemos nossos amigos. (Churton Collins)',
    'A felicidade não está em fazer o que a gente quer, e sim querer o que a gente faz. (Jean Paul Sartre)',
    'Nada acontece a menos que sonhemos antes. (Carl Sandburg)',
    'É sempre divertido fazer o impossível. (Walt Disney)',
    'A coisa mais cara é transformar um cliente insatisfeito em satisfeito. (Jan Carlzon)',
    'Experiência é o nome que cada um dá a seus erros. (Oscar Wilde)',
    'Lembre sempre que a sua vontade de triunfar é mais importante do que qualquer outra coisa. (Abraham Lincoln)',
    'Prefiro os erros do entusiasmo à indiferença da sabedoria. (Anatole France)',
    'Na realidade, vendas e serviços são inseparáveis. (Carter Brow)',
    'A arte de ser ora audacioso, ora prudente, é a arte de vencer. (Napoleão Bonaparte)',
    'Seja corajoso.Mesmo que você não seja, finja ser. Ninguém nota a diferença. (H.Jackson Brown Jr.)',
    'Não somos responsáveis apenas pelo que fazemos, mas também pelo que deixamos de fazer. (Moliere)',
    'A estratégia de marketing começa, termina, vive e morre com o cliente. (Michael Gerber)',
    'Quando você contrata pessoas mais inteligentes do que você, prova que é mais inteligente do que elas. (R. H. Grant)',
    'O talento vence jogos, mas só o trabalho em equipe vence campeonatos. (Michael Jordan)',
    'Um negócio nunca é bom se com ele conseguimos um inimigo. (Hugh Prather)',
    'Um objetivo nada mais é do que um sonho com limite de tempo. (Joel L. Griffith)',
    'Sorte é o que acontece quando a preparação encontra a oportunidade. (Elmer Letterman)',
    'O mercado dita inovações. Quem não segue vira peça de museu. (Phill Knight)',
    'O único lugar que o sucesso vem antes do trabalho é no dicionário. (Vidal Sasson)',
    'Se você quiser ir daqui para lá no mundo dos negócios, não encontrará nenhuma linha reta para levá-lo. (William Ahmanson)',
    'Integridade é a essência de todo negócio. (R. Buckminster Fuller)',
    'Existe o risco que você jamais pode correr. Existe o risco que você jamais pode deixar de correr. (Peter Drucker)',
    'As duas coisas mais importantes não aparecem no balanço da empresa: sua reputação e o seu time. (Henry Ford, adaptação)',
    'A qualidade do seu trabalho tem tudo a ver com a qualidade da sua vida. (Orison Swett Marden)',
    'Nenhuma empresa pode ter sucesso tentando tudo para todos. (Michael Treacy)',
    'Nunca se esqueça de um cliente; e nunca deixe que um cliente esqueça você. (Walter Reuther)',
    'Somos o que repetidamente fazemos. Portanto, a excelência não é um feito, é um hábito. (Aristóteles)',
    'Persistência é irmã gêmea da excelência. Uma é mãe da qualidade, a outra a mãe do tempo. (Marabel Morgan)',
    'O propósito de uma companhia é criar e manter o cliente. (Theodoro Levitt)',
    'Comemore os seus sucessos. Veja com humor os seus fracassos. (Sam Walton)',
    'Autorrespeito, autoconhecimento e autocontrole conduzem a vida ao poder supremo. (Alfred Tennyson)',
    'É tentando o impossível que se chega à realização do possível. (Henri Barbusse)',
    'Ganharão o jogo empresas que têm como missão exceder as expectativas dos clientes. (Richard Whiteley)',
    'Toda empresa precisa ter gente que erra, que não tem medo de errar e que aprende com erro. (Bill Gates)',
    'A confiança em si mesmo é o primeiro segredo do sucesso. (Ralph Waldo Emerson)',
    'Aquele que pretende ser um líder tem que ser uma ponte. (Provérbio Galês)',
    'Sempre que se vê um empreendimento de sucesso é porque alguém antes tomou uma decisão destemida. (Peter Ducker)',
    'Serviços aos clientes é uma estratégia de marketing. (John Tschohl)',
    'Muda tuas ideias e mudarás teu mundo. (Norman Vincent Peale)',
    'Sua tarefa como líder é criar uma atmosfera que transforme o antagonismo em energia criativa. (John Kao)',
    'A publicidade traz os clientes até a porta; mas o mau serviço envia eles direto para fora. (John Tschohl)',
    'Único cliente bom é o cliente feliz. Lembre-se: clientes felizes adoram gastar dinheiro. (Daryl Bernstein)',
    'Devemos prometer somente aquilo que podemos entregar e entregar mais do que prometemos. (Jean Rozwadowski)',
    'Nada de importante no mundo foi realizado sem paixão. (Georg Wilhelm)',
    'Quem tem a obrigação de visualizar o futuro não é o cliente. (Célia Chaim)',
    'Profissional nota 10 é aquele que tem 2 pontos de esforço, 3 pontos de talento e 5 pontos de caráter. (Roland Barthes)',
    'Uma das melhores maneiras de convencer os outros é ouvindo. Ouça todos. (Dean Rusk)',
    'O importante é mudar sempre, mesmo que estejamos crescendo e ganhando o jogo. (Masaaki Imai)',
    'Sempre que você vai encontrar um cliente você é a empresa. (Barrie Hopson e Mike Scally)',
    'Se não puder destacar-se pelo talento, vença pelo esforço. (Dave Weinbaum)',
    'Em busca do ótimo não se faz o bom. (Segundo Mandamento da TAM)',
    'Se existe uma forma de fazer melhor, descubra-a. (Thomas Edison)',
    'Fechar os olhos e os ouvidos para o cliente é uma loucura. É um suicídio empresarial. (Sérgio Almeida)',
    'Não deixe o ruído das opiniões dos outros abafar a sua própria voz interior. (Steve Jobs)',
    'Somente os que ousam errar muito podem realizar muito. (John F. Kennedy)',
    'Aceite os desafios para que possa sentir o sabor da vitória. (General George S. Patton)',
    'A sorte favorece a mente preparada. (Louis Pasteur)',
    'Quando os momentos da verdade não são gerenciados, o serviço regride até a mediocridade. (Karl Albrecht)',
    'Metas são necessárias não só para nos motivar, mas para nos manter vivos. (Robert H. Schuller)',
    'Pessoas com meta têm sucesso pois sabem onde estão indo. (Earl Nightingate)',
    'A pessoa comum é exigente com os outros. A superior é exigente consigo mesmo. (Marco Aurélio, adaptado)',
    'Não há sucesso sem dificuldade. (Sófocles)',
    'Os clientes julgam os serviços pela maneira que são tratados por aqueles com quem tem contato. (Carl Sewell)',
    'Um grande prazer na vida é fazer aquilo que dizem que você não é capaz de fazer. (Walter Gagehot)',
    'Toda glória advém de ousar começar. (Eugene F. Ware)',
    'Todas as pequenas coisas, juntas, formam uma base de clientes fiéis e mais lucrativas. (Bruce Hammonds)',
    'A pessoa que não acredita em si mesmo não acredita em mais nada. (Roy L. Smith, adaptado)',
    'Grandes mentes estão prontas não apenas para explorar oportunidades, mas para criá-las. (Cotton)',
    'O primeiro passo indispensável para conseguir coisas na vida é decidir o que você quer. (Ben Stein)',
    'A percepção quando chega a ser julgada por outros é a realidade. (Jack Lowenstein)',
    'O pior fracassado do mundo é aquele que perdeu o entusiasmo. (H. W. Arnold)',
    'A maior recompensa pelo trabalho não é o que a pessoa ganha, é o que ela se torna através dele. (John Ruskin)',
    'Quando as expectativas aumentam inicia-se um ciclo interminável e contínuo de melhoria. (Steven Hronec)',
    'Aquele que cometeu um erro e não corrigiu está cometendo outro erro. (Confúcio)',
    'A vitória sempre foi de quem nunca duvidou dela. (Raul Follerean)',
    'Os satisfeitos nada mais fazem. Os insatisfeitos são os únicos propulsores do mundo. (Walter Savage Landor)',
    'Todas as coisas são possíveis àqueles que creem. (S. Marcos, 11:23)',
    'O problema é que a maioria das pessoas prefere um elogio que prejudique do que uma crítica que beneficie. (Norman Vincent Peale)',
    'A decepção surge da disparidade entre a expectativa de uma experiência agradável e a experiência real. (Albert Hirschman)',
    'Prefiro a angústia da busca do que a paz da acomodação. (Dom Resende Costa)',
    'Os únicos limites das pessoas são o tamanho de suas ideias e o grau de sua dedicação. (F. Veiga, adaptado)',
    'Conhecimento não é aquilo que você sabe, mas o que você faz com aquilo que sabe. (Aldous Huxley)',
    'Fidelidade do cliente é a chave para lucratividade e crescimento futuro. (Rick Tate)',
    'Critica o que fazes, e não faças o que criticas. (Provérbio Árabe)',
    'O que merece ser feito, merece ser bem feito. (Lord Chesterfield)',
    'Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se. (Henry Ford)',
    'Para evitar críticas: não faça nada, não diga nada, não seja nada. (Elbert Hubbard)',
    'As pessoas abominam a impessoalidade do negócio. (Marcos Gouvêa de Souza)',
    'Nunca aceite o ‘não’ como resposta. (J. F. Mitchell)',
    'A natureza nos deu uma língua e dois ouvidos para que ouçamos mais do que falamos. (Diógenes Laércio)',
    'Se você não puder manter, não proponha nada; esta é a regra básica na satisfação do cliente. (Sérgio Almeida)',
    'Feliz aquele que sabe adquirir experiência com o erro dos outros. (Kauto)',
    'Querer ser de seu tempo é já estar ultrapassado. (Eugène Ionesco)',
    'Planeje o seu trabalho hoje para todos os dias trabalhar o seu plano. (Norman Vincent Peale)',
    'Supere a expectativa do cliente com pequenas ações frequentes e não solicitadas. (David Freemantle)',
    'Sucesso é apenas sorte; pergunte para qualquer fracassado. (Earle Wilson)',
    'Destino não é exterior a nós; somos nós que criamos nosso próprio destino dia após dia. (Henry Miller)',
    'O homem que removeu a montanha começou carregando as pedras. (Provérbio chinês)',
    'O gosto amargo da baixa qualidade dura bem mais do que a doçura do preço inferior. (Heinz Rahnan)',
    'A covardia é o medo aceito; a coragem é o medo dominado. (Lecouve)',
    'Todos os dias me levanto para vencer. (Onassis)',
    'Meu sucesso se deve ao fato de me cercar de pessoas competentes. (Enzo Ferrari)',
    'Não atrase o seu progresso com medo de fracassar. (Nathiel Hover)',
    'As pessoas são a força direcional por trás do crescimento. (Business Week)',
    'Quem não tem inteligência para criar tem que ter coragem para copiar. (Sétimo Mandamento da TAM)',
    'Ninguém pode ferir você sem o seu consentimento. (Eleanor Roosvelt)',
    'O verdadeiro risco é não fazer nada. (Denis Waitley)',
    'Aquele que domina os outros é forte; aquele que domina a si mesmo é todo-poderoso. (Lao Tsu)',
    'Faça o que puder, com o que tiver, onde estiver. (Theodore Roosvelt)',
    'A qualidade do serviço e produto é decorrência da qualidade das pessoas. (Claus Moller)',
    'Nossas dúvidas são traidoras e nos fazem perder, por medo de tentar, o que poderíamos ganhar. (William Shakespeare)',
    'Os problemas são apenas oportunidades com roupas de trabalho. (Henry John Kaiser)',
    'Não nos transformamos de uma hora para outra aquilo que não cooperamos para nos tornar. (William J. Bennett)',
    'O que a pessoa pensa a respeito de si mesmo indica o seu destino. (Henry David Thoreau, adaptado)',
    'Decidir o que não fazer é tão importante quanto decidir o que fazer. Isso é verdadeiro para companhias e também para produtos. (Steve Jobs)',
    'O cliente precisa saber que nós nos importamos com ele. (Roberto Maksoud)',
    'Devemos ser a mudança que queremos ver no mundo. (Gandhi)',
    'Você tem que fazer as coisas que pensa não ser capaz de fazer. (Eleanor Roosvelt)',
    'Em toda a iniciativa, considere aonde você poderia chegar. (Publilius Syrus)',
    'Ninguém pode construir uma reputação com base naquilo que ainda vai fazer. (Henry Ford)',
    'A comunicação é a principal fonte de poder pessoal. (Fortune Magazine)',
    'Falhar no planejamento é um planejamento para falhar. (Effie Jones)',
    'Em todas as situações, deve-se considerar o objetivo. (Jean de La Fontaine)',
    '65% dos negócios de uma empresa vêm de clientes já existentes – não de novos. (AMA)',
    'É o motivo que engrandece a ação; é o fazer, não o feito. (Margaret Preston)',
    'Quem vive sem disciplina morre sem honra. (Provérbio islandês)',
    'Mesmo se você estiver no caminho certo será atropelado se ficar sentado nele. (Will Rogers)',
    'Desperdiçar o próprio tempo é uma espécie de suicídio. (George Savile)',
    'A ética dá lucro para a empresa. (Lori Tansey)',
    'O fanatismo consiste em redobrar esforços quando o objetivo for esquecido. (George Santayana)',
    'Se você não sabe para onde vai, provavelmente terminará em algum outro lugar. (Laurence J. Peter)',
    'Os atrasos deixam o cliente com os dentes rangendo. (Fred Wiersema)',
    'Uma jornada de mil quilômetros começa pelo primeiro passo. (Lao Tsu)',
    'Algumas derrotas são mais triunfantes do que vitórias. (Michael de Montaigne)',
    'Nossa vida é o que os nossos pensamentos fazem dela. (Marco Aurélio Antonino)',
    'Quem torna as coisas mais fáceis para os outros, torna as coisas mais fáceis para si. (Ditado asiático)',
    'Custa 6 vezes mais conquistar um novo cliente do que manter um antigo. (Claus Moller)',
    'Seja um parâmetro de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde a excelência é esperada. (Steve Jobs)',
    'Coragem é estar morto de medo e encilhar o cavalo mesmo assim. (John Wayne)',
    'O talento sempre tem consciência de sua própria abundância e não cria objeções em dividir. (Alexander Soljenitsyn)',
    'Não se pode progredir enquanto se ajustam contas. (Dick Armey)',
    'O único bem coletivo é aquele que assegura o bem individual de cada cidadão. (Charles Dickens)',
    'Ouça, ou sua língua vai conservar sua surdez. (Provérbio indígena norte-americano)',
    'O que você dá é o que você recebe. (Eric Berne)',
    'Sucesso é a soma de pequenos esforços repetidos dia sim, e no outro também. (Robert Collier)',
    'É bom ter objetivo para a jornada à frente; mas, no fim, a jornada é o que importa. (Ursula L. Le Guin)',
    'Jamais imponha a sua linguagem às pessoas com as quais você deseja se comunicar. (Abbie Hoffman)',
    'Você tem que escutar os clientes e então agir com base no que eles disseram. (Charles Lazarus)',
    'As pessoas só vêem aquilo que estão preparadas para ver. (Ralph Waldo Emerson)',
    'Quem só conhece o seu lado do problema sabe pouco sobre ele. (John Stuart Mill)',
    'Duas cabeças são melhores do que uma. (John Heywood)',
    'Uma ideia pode virar pó ou mágica, depende do talento que esbarra nela. (William Bernbach)',
    'A empresa que busca encantar o cliente é inquieta e criativa. (Sérgio Almeida)',
    'A oposição traz concórdia. A discórdia vem da mais perfeita harmonia. (Heráclito)',
    'Não busque todas as qualidades em uma pessoa só. (Confúcio)',
    'Ter senso de humor é tão importante quanto ter talento. (Gary Oldman)',
    'Todos nós somos ignorantes, só que em assuntos diferentes. (Will Rogers)',
    'O plano de só uma pessoa pode ser incompleto; o de duas será melhor. (Chuang-tsé, adaptado)',
    'Ninguém jamais ganha uma discussão com o cliente. (Barrie Hopson)',
    'O hoje é aluno do ontem. (Thomas Fuller)',
    'Jamais devemos negociar por medo, mas jamais devemos ter medo de negociar. (John F. Kennedy)',
    'O tratamento deve sempre ser positivo, independente da circunstância. (Fábio Eltz)',
    'Não tenha medo de tempestades, pois estarás aprendendo a manejar o barco. (Louisa May Alcott)',
    'Se você pensa que educação é uma coisa cara, tente a ignorância. (Derek Bok)',
    'A coisa mais difícil é a decisão de agir, o resto é apenas tenacidade. (Amelia Earhart)',
    'O autodesenvolvimento é um dever maior do que o auto-sacrifício. (Elizabeth Cady Stanton)',
    'Grandes descobertas e progressos envolvem a cooperação de várias mentes. (Alexander Graham Bell)',
    'É preciso buscar fatias na multidão. (Sérgio Quartiermeister)',
    'Caia 7 vezes. Levante-se 8. (Provérbio japonês)',
    'Ninguém nasce um gênio; a pessoa se torna um. (Simone de Beauvoir)',
    'Quando eu deixar de ser o que sou, eu irei me tornar o que poderia ser. (Lao Tzu)',
    'Seu tempo é limitado, então não o gaste vivendo a vida de outra pessoa. (Steve Jobs)',
    'A mente humana, expandida por uma ideia nova, jamais retorna à dimensão original. (Oliver Wendell Holmes)',
    'A percepção é um ponto de vista individual. Portanto, não se discute. (Sérgio Almeida)',
    'Você deve guardar um dragão dentro de si. Quando precisar, você deixa o dragão sair. (Anderson Silva)',
    'Eu preferiria morrer de paixão do que de tédio. (Vincent Van Gogh)',
    'Sonhar, afinal, é uma forma de planejamento. (Gloria Steinem)',
    'O segredo do sucesso é a constância do objetivo. (Benjamin Disraeli)',
    'Escreva algo que valha a pena ler, ou faça alguma coisa que valha a pena escrever. (Benjamin Franklin)',
    'Saber ouvir e ter equilíbrio emocional: fundamentais no atendimento ao cliente. (Fela Moscovici)',
    'É preciso ter dúvidas. Só os estúpidos têm uma confiança absoluta em si mesmos. (Orson Welles)',
    'Devemos crer que somos dotados de alguma coisa, e que essa coisa, deve ser atingida a todo custo. (Marie Curie)',
    'Tudo tem beleza. Mas nem todos podem ver. (Confúcio)',
    'Prometa o que não irá cumprir e seus clientes formarão um mau conceito a seu respeito. (Robert Peterson)',
    'Se o índice de falha é de 1 em 1 milhão, o que você responde para esse cliente? (Pôster da IBM)',
    'Se você deseja que seus filhos acabem bem, gaste o dobro de tempo com eles, e metade do dinheiro. (Abigail Van Buren)',
    'Use bom senso em todas as situações; não espere por regras novas, pois não virão. (Manual da Nordstrom)',
    'Todo mundo tem talento, é só uma questão de se mexer até descobrir qual. (George Lucas)',
    'Quanto mais nos defrontamos com tecnologia, maior nosso anseio por contatos humanos. (John Nasbit)',
    'Bem começado é meio caminho andado. (Provérbio grego)',
    'A mente é tudo. Você se torna aquilo que você pensa. (Buddha)',
    'Uma queixa é alguém avisando que você não o satisfez. E isso é escrito em ouro. (Donald Beaver Jr.)',
    'O medo de ousar, ser agressivo ou inovar fechou mais empresas do que a ousadia. (Júlio Ribeiro)',
    'Minha primeira mensagem é: escute, escute e escute o pessoal que faz o trabalho. (H. Ross Perot)',
    'A preguiça caminha tão devagar que a pobreza a alcança com rapidez. (Franklin D. Roosvelt)',
    'Dos clientes insatisfeitos, apenas 5% efetivamente fez uma reclamação. (Denis Walker)',
    'Vá na direção de seus sonhos. Viva a vida que você imaginou. (Henry David Thoreau)',
    'Não existe empresa nota 10 com empregados nota 5. (Marcos Gouvêa de Souza)',
    'Perder tempo é um castigo insuportável. (Quin Guanshu)',
    'Serviços ao cliente não consistem em satisfação, mas sim em deslumbre. (Chip Bell)',
    'Você pode destruir o seu hoje se preocupando com o amanhã. (Janis Joplin)',
    'Todo cliente quer ser tratado como especial, não quer ser mais um. (Fábio Eltz)',
    'Começar é a parte mais importante de qualquer trabalho. (Platão)',
    'Nossa meta é resolver problemas antes que os clientes saibam que eles existam. (Ron Bern)',
    'Uma boa cabeça e um bom coração formam sempre uma combinação formidável. (Nelson Mandela)',
    'Se você não tem item de controle, você não tem gerência. (Kaoru Ishikawa)',
    'Os colaboradores evitam as queixas pois eles nunca foram instruídos a lidar com elas. (John Tschohl)',
    'O maior prêmio que a vida oferece é trabalhar em algo que valha a pena. (Theodore Roosvelt)',
    'Um bom porta-voz transforma leite desnatado em chantilly. (George Lichtenberg)',
    'Um líder genuíno é motivador: orienta as pessoas, não as dirige; envolve, não as coage. (J. Walters)',
    'A vida não é sobre ter, é sobre dar e ser. (Kevin Kruse)',
    'O resultado final de um serviço é um sentimento. (Karl Albrecht)',
    'O objetivo do marketing de relacionamento é a retenção de clientes. (Terry Vavra)',
    'Aqueles que nada fazem estão sempre dispostos a criticar os que fazem algo. (Paul Deschanel)',
    'Cliente é todo aquele impactado por seus produtos, processos e serviços. (Juran)',
    'As empresas terão de adaptar-se às preferências individuais de cada consumidor ou sucumbirão. (Raimar Richers)',
    'Sente-se sufocado aquele sem um objetivo de vida. (Fiódor Dostoiévski)',
    'Não critique a pessoa, somente o comportamento. (Claus Moller)',
    'É doce deixar a mente relaxar de vez em quando. (Horácio)',
    'O presente é o único momento que temos para fazer algo. (Ken O’Donnell)',
    'Todo mundo é capaz de dominar uma dor, exceto quem a sente. (William Shakespeare)',
    'Desperdício é tudo aquilo que não representa valor para o cliente. (Richard Whiteley)',
    'A convicção é inútil – a menos que se transforme em conduta. (Thomas Carlyle)',
    'Quanto mais distante o administrador do administrado, menos eficiente a administração. (Phillip Crosby)',
    'A felicidade não é algo pronto. Ela vem de suas próprias ações. (Dalai Lama)',
    'Devemos seguir o exemplo dos rios: dão suas águas ao mar e nunca ficam vazios. (Jefferson Leão de Almeida)',
    'Meu maior poder como consultor é ser ignorante e fazer algumas perguntas. (Peter Drucker)',
    'O cliente é alguém que nos traz suas necessidades. (L. L. Bean Inc)',
    'O pior erro que você pode cometer em sua vida é ficar com medo de cometer algum erro. (Elbert Hubbard)',
    'Se houver uma opção melhor, os clientes mudarão de fornecedor. (Catherine Romano)',
    'O alvo na vida não deve ser ultrapassar os outros, mas sim ultrapassar a nós mesmos. (M. J. Babcock)',
    'Quando são cometidos lapsos nos serviços, as vendas caem. (Terrell Harris)',
    'Jamais prometa mais do que pode fazer. (Publilius Syrus)',
    'Se você for direto e honesto com seus clientes eles o tratarão como amigo. (Milton Moore)',
    'Não arriscar nada é arriscar tudo. (Cesare Cantú)',
    'Não se comprometa a fazer o que não é capaz, mas preocupe-se em manter sua promessa. (George Washington)',
    'Quando você atende ao telefone, a imagem da sua empresa é percebida do outro lado da linha. (Video Business Magazine)',
    'Um investimento em conhecimento sempre paga o maior juro. (Benjamin Franklin)',
    'Contrate o tipo de pessoa capaz de construir relações sólidas com os clientes. (Lunda Goldzimer)',
    'Não abandone suas três grandes e inabaláveis amigas: a intuição, a inocência e a fé. (George Gurdjieff)',
    'Quem sabe faz a hora, não espera acontecer. (Geraldo Vandré)',
    'A única coisa que sabemos sobre o futuro é que ele será diferente. (Peter Drucker)',
    'Quando você perde um cliente, perde transações futuras e propaganda boca a boca. (David Clutterbuck)',
    'Eu me sentia derrotado por não ter sapatos, até o dia que encontrei um homem que não tinha pés. (Harols Abbott)',
    'Uma empresa que não escuta o seu cliente está fadada ao insucesso. (Paulo Apsan)',
    'Se você não é notado, você não tem nada. (Leo Burnett)',
    'Não são os anos de sua vida que contam. É a vida em seus anos. (Abraham Lincoln)',
    'O marketing de relacionamento reduz o impacto dos esforços feitos pela concorrência. (Don Peppers)',
    'É melhor ser invejado do que lastimado. (Heródoto)',
    'Você pode construir o mais belo lugar do mundo, mas serão as pessoas que tornarão realidade o sonho. (Walt Disney)',
    'Não existe técnica de comunicação mais relevante do que a naturalidade. (Reinaldo Polito)',
    'Na vida sempre fazemos escolhas. Ainda que escolhemos não escolher. (Carmen Miranda)',
    'A melhor maneira de vender é facilitando a compra. (Sales and Marketing Magazine)',
    'A cortesia tem um grande poder, e não custa nada. (Samuel Smiles)',
    'Você pode ficar desapontado se falhar, mas já está derrotado se não tentar. (Beverly Sills)',
    'Se souber o nome do cliente, use em sua saudação. (Texas American Bank)',
    'Ofereça ao cliente algo que vale a pena e ele pagará o que vale. (Tom Peter e Nancy Austin)',
    'Seja hoje melhor do que ontem e, amanhã, melhor do que hoje. (Constantino C. Vigil)',
    'O acordo é o último recurso dos que não têm imaginação. (Oscar Wilde)',
    'Lucro é vital, mas o cliente vem antes. Sem ele não há lucro. (Richard Whiteley)',
    'Sonhe grande e se atreva a falhar. (Norman Vaughan)',
    'Eu sempre uso o produto dos meus clientes; não é bajulação, mas boas maneiras. (David Ogilvy)',
    'Traga novas ideias e trate-as regiamente, pois uma delas pode ser o rei. (Mark van Doren)',
    'Quem quer agradar a todo mundo não agrada a ninguém. (Dito popular)',
    'Leve é a tarefa quando muitos dividem o trabalho. (Samuel Johnson)',
    'Você seria seu próprio cliente? (Linda Goldzimer)',
    'Ganhar não é tudo, mas querer ganhar é. (Vince Lombardi)',
    'Aquilo que você não pode medir não pode ser aperfeiçoado. (John Young)',
    'O conveniente e o correto raramente são a mesma coisa. (Charles Brower)',
    'A confiabilidade do serviço é fator mais importante de todos, duas vezes acima dos demais. (Gordon Spainhower)',
    'Uma pessoa que nunca cometeu um erro, nunca tentou nada de novo. (Albert Einstein)',
    'Você precisa ver seus erros para poder fazer algo a respeito deles. (Claus Moller)',
    'Se os ventos não vão servir, leve os remos. (Provérbio norte-americano)',
    'Ninguém cativa um cliente sabendo apenas o nome e onde ele mora. (Sérgio Quartiermeister)',
    'O trabalho de adivinhação torna inevitável a insatisfação. (John Tschohol)',
    'Quando deixamos de contribuir, começamos a morrer. (Eleanor Roosvelt)',
    'A chave do negócio é analisar cada cliente antes de servi-lo. (Laurent Svadon)',
    'O problema não é o problema. O problema é a atitude com relação ao problema. (Kelly Young)',
    'Verifique seus sentimentos à porta do escritório. (Tom Peters)',
    'Diga ‘obrigado’ sempre que tiver uma oportunidade. (Carl Sewell)',
    'Você nunca vai chegar ao seu destino se você parar e atirar pedras em cada cão que late. (Winston Churchill)',
    'A confiança dos clientes é o ativo mais valioso de uma companhia de serviços. (Leonard Berry)',
    'Não ergas um edifício sem fortes alicerces ou viverás com medo. (Sabedoria Persa)',
    'Trate seus funcionários assim como quer que eles tratem seus melhores clientes. (Stephen Covey)',
    'Somos damas e cavalheiros servindo damas e cavalheiros. (Lema do Ritz-Carlton Hotel)',
    'Esforce-se para não ser um sucesso, mas sim para ser valioso. (Albert Einstein)',
    'Projete um sistema que equilibre processo, produto e medidas de satisfação. (Peter Francese)',
    'Ouça qualquer um que tenha uma ideia original. Encoraje-o. Deixe as pessoas continuarem suas ideias. (William McKnight)',
    'Satisfaça o cliente no começo, no fim e sempre. (Phillip Crosby)',
    'Eu não falhei no teste. Eu só encontrei 100 maneiras de fazer errado. (Benjamin Franklin)',
    'Quer segurança em um emprego? Faça um cliente feliz. (Júlio Lobos)',
    'O essencial é invisível aos olhos. (Antoine de Saint-Exupéry)',
    'Conheça seus clientes como sua família, satisfaça-os e você terá sucesso. (Richard Whiteley)',
    'Um cliente que reclama é um consultor. Aponta o que melhorar e não cobra nada por isso. (Sérgio Almeida)',
    'Nunca é tarde demais para ser o que você poderia ter sido. (George Eliot)',
    'Não existe melhor publicidade do que um cliente satisfeito. (Jay Curry e Ludovic Stora)',
    'Gerenciar não é mais a direção da coisa, mas o aperfeiçoamento das pessoas. (Alvin Toffler)',
    'A pessoa no comando não pode apenas pregar. Ela precisa liderar com exemplos. (Carl Sewell)',
    'A marca é um símbolo que identifica uma promessa na cabeça do cliente. (Larry Light)',
    'Não há saber mais ou saber menos: há saberes diferentes. (Paulo Freire)',
    'O papel do gerente é de orientar, energizar e estimular. (Jack Welck)',
    'Se você quiser se levantar, levante outra pessoa. (Booker T. Washington)',
    'Você pode tosquiar o carneiro por muitos anos, mas poderá esfolá-lo somente uma vez. (John Sewell)',
    'Quanto maior a dificuldade maior é o mérito de superá-la. (H. W. Beecher)',
    'Cuidar o lado emocional do cliente é mais importante do que consertar um equipamento. (Bill Bleuel)',
    'O cliente compra uma promessa e são obrigados a confiar que a empresa ira cumpri-la. (Leonard Berry)',
    'A questão não é quem vai me deixar; mas sim, quem vai me impedir. (Ayn Rand)',
    'Certifique-se de que suas palavras e seus atos estão em harmonia. (Claus Moller)',
    'As pessoas estão atentas a você. A qualidade está no seu coração. (Steven Leonard Jr.)',
    'Nossa paciência conquistará mais do que a nossa força. (Edmund Burke)',
    'Se os clientes não estão reclamando você está perdendo a oportunidade de ser melhor. (Karl Albrecht)',
    'Você pode mudar sem crescer, mas não pode crescer sem mudar. (Larry Wilson)',
    'Agradeça com um sorriso a presença do cliente. (Texas American Bank)',
    'Você não crescerá a não ser que tente algo além daquilo que já domina. (Ronald Osborn)',
    'Faça a voz do cliente ecoar em toda a empresa. (Richard Whiteley)',
    'Tudo o que você sempre quis está do outro lado do seu medo. (George Addair)',
    'Nada contribui tanto para clarear a mente do que um objetivo claro. (Marry W. Shelley)',
    'Um único pensamento pode revolucionar sua vida. (Norman Vincent Peale)',
    'Todo o marketing da sua empresa pode ser anulado por um único empregado grosseiro. (John Tschohl)',
    'Quando compreende-se o que o cliente deseja, torna-se mais fácil atendê-lo. (Fábio Eltz)',
    'Só serão felizes aqueles que procurarem e encontrarem um meio de servir. (Albert Schweitzer)',
    'A percepção que o cliente tem em relação ao seu produto é o que determina sua satisfação. (Linda Goldzimer)',
    'O mais corajoso dos atos ainda é pensar com a própria cabeça. (Coco Chanel)',
    'A coisa mais importante para o cliente é: você fez aquilo que prometeu? (Carl Sewell)',
    'Nada que valha a pena acontece a alguém exceto o resultado do trabalho árduo. (Booker T. Washington)',
    'A forma mais barata de manter clientes satisfeitos é servi-los bem desde o começo. (Fortune Magazine)',
    'A melhor forma de ter clientes para sempre é oferecer a eles um negócio irrecusável. (Don Peppers)',
    'Tenho aprendido ao longo dos anos que, quando a mente está pronta, isso diminui o medo. (Rosa Parks)',
    'O cliente é o chefe. (Lema da Bio-Lab)',
    'Mestre não é quem sempre ensina, mas quem de repente aprende. (João Guimarães Rosa)',
    'Se não agrega valor, pare; se faz sentido para o cliente, prossiga. (Bob Harbage)',
    'Os clientes sempre reconhecem quando alguém saiu do seu caminho para ajudá-los. (Leonard Berry)',
    'Espíritos grandiosos sempre encontraram oposição violenta de mentes medíocres. (Albert Einstein)',
    'A busca da qualidade é um estado de espírito. (Cesare Romiti)',
    'O que é realmente necessário em empresa que presta serviço são pessoas que gostem de pessoas. (Frank Petro)',
    'É importante aprender a não se aborrecer com opiniões diferentes das suas. (Bertrand Russell)',
    'O melhor vendedor do mundo é um cliente encantado. (Sérgio Almeida)',
    'Ter problemas na vida é inevitável. Ser derrotado por eles é opcional. (Roger Crowford)',
    'Limitar o foco ao cliente provoca uma espécie de cegueira para inovações. (Paulo Apsan)',
    'A prestação de bons serviços nunca é acidental. (Jaclyn Jeffrey)',
    'Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa. (Cristóvão Colombo)',
    'O que pode sair errado? Essa é a pergunta a se fazer ao projetar os seus sistemas. (Carl Sewell)',
    'Toma conta do teu negócio ou ele tomará conta de ti. (Benjamin Franklin)',
    'A satisfação do cliente é uma relação entre o que ele viu e o que ele esperava ver. (Sérgio Almeida)',
    'Perde tudo quem perde o momento certo. (Provérbio espanhol)',
    'Combata a mediocridade – em si e nos outros. (Claus Moller)',
    'Lembre-se que não conseguir o que você quer é algumas vezes um lance de sorte. (Dalai Lama)',
    'Uma atitude vitoriosa é meio caminho andado para o sucesso. (Arthur Riedel)',
    'Agregar valor é resolver os problemas do cliente. (James Belasco)',
    'Fazer rápido obriga-o a fazer certo logo na primeira vez. (John Young)',
    'Devemos preferir as queixas aos cumprimentos. (Donald Beaver Jr.)',
    'Todos os sorrisos do mundo não irão ajudá-lo se o produto ou serviço não for o que o cliente deseja. (Carl Sewell)',
    'Um serviço excelente é uma estratégia de lucro. (Leonard Berry)',
    'Você pode tudo se tiver entusiasmo. (Henry Ford)',
    'Não sei aonde vou, mas já estou no caminho. (Carl Sandburg)',
    'Conte a verdade – ou não conte nada. Ninguém gosta de gente mentirosa. (Fortune Magazine)',
    'O insucesso é uma oportunidade para recomeçar com mais inteligência. (Henry Ford)',
    ];
  }
}
